### ISSUE TITLE
Retrieve description from device

### ISSUE THREAD

**Issue by sproctor** [ivanempire/lighthouse#13]
This one is a bit big, relies on my previous work, and makes a few fixes that I noticed while writing the tests, so I won't make a PR for now.

See ec10d11

A couple of notes:

- There's no distinction between root and embedded devices in the spec. See section 2.3: https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf
- This adds dependencies on Ktor, Kotlin serialization, and XmlUtil.
- I didn't implement the icon list.
- There should probably be proguard rules to keep the annotation and class members for the classes marked `@Serializable`.
- Ignore the soap envelope class. I started reading at the wrong part of the spec. Handling SOAP actions probably isn't that interesting.

**Comment by ivanempire** [comment]
Yep, this was on my radar, and I have a placeholder variable in there for this, but this isn't getting integrated any time soon - I may just stick to discovery only for Lighthouse.

**Comment by ivanempire** [comment]
Deleted older comment to type something more descriptive now. Not directly into Lighthouse, but moving the descriptive classes over to a new artifact and having that contain all the required network dependencies is an idea. It's something I thought of when I saw what Room was doing for  its Rx, Flow, and Guava adapters [here](https://developer.android.com/training/data-storage/room). Closing for now since this will add too many additional dependencies into Lighthouse for only the discovery step.

**Comment by sproctor** [comment]
Let's put some perspective on this. The biggest change is the amount of maintenance in updating ktor/xmlutil versions. If someone doesn't use it, it should be removed by proguard/R8.

For me, this is absolutely necessary. I'm only using SSDP to get friendly names for cameras. WS-Discovery requires authentication to get the friendly name from AXIS (and presumedly other) cameras. I have this working now. If you add this, I can use your version, otherwise I'll stick with mine, so it's not very important to me that this gets merged.

**Comment by ivanempire** [comment]
Let me give it some more thought on how I want this implemented, but use your version to unblock your work, but this will be added to the library because, I mean, all of the classes are scaffolded already.
