### ISSUE TITLE
Getting USN or NT

### ISSUE THREAD

**Issue by smalldevcloud** [ivanempire/lighthouse#30]
In the logcat, the log shows that the package has the fields I need. But AbridgedMediaDevice no longer contains them. Can I somehow get them, other than from the logger message?
![image](https://github.com/ivanempire/lighthouse/assets/80459916/14ae9ea6-0a4f-4651-b079-04a711384df4)

**Comment by ivanempire** [comment]
Hey ya!
Well you'll get part of it (the UUID) via `AbridgedMediaDevice.uuid`, but the rest is dropped in this case because it doesn't look like the device follows the SSDP spec.

The `NT` value is missing the `service` marker, and the `USN` value is missing the `device` marker (see page 29 of the PDF at the start of the ReadMe, but also attached screenshots), which means that the result is assumed to target the root component. This is where the fall-through happens: https://github.com/ivanempire/lighthouse/blob/main/lighthouse/src/main/java/com/ivanempire/lighthouse/models/packets/UniqueServiceName.kt#L52
<img width="837" alt="image" src="https://github.com/ivanempire/lighthouse/assets/1571060/070fb417-660d-4eae-8452-3ed783bea7b6">
<img width="734" alt="image" src="https://github.com/ivanempire/lighthouse/assets/1571060/d8314612-940c-4776-b571-c3ff8948ecd5">
Having said that, if a device does follow the spec, `AbridgedMediaDevice` has `serviceList` and `deviceList` fields, which provide access to the "deconstructed" information from said packets.

**Comment by smalldevcloud** [comment]
Thanks a lot!

**Comment by ivanempire** [comment]
Sure! Closing for now but let me know if you'd need any additional input - would be more than happy to add a unit test for that device once it's spec-ready 👍
