### ISSUE TITLE
USN should accept any string as UUID

### ISSUE THREAD

**Issue by sproctor** [ivanempire/lighthouse#4]
See https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf section 1.1.4.

According to that, UPnP 1.0 can give any string for the UUID. It's ugly, but that is my experience.

Response from AXIS camera:

```
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Wed, 22 Mar 2023 22:19:47 GMT
EXT:
LOCATION: http://192.168.0.209:49152/rootdesc1.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 44f2f88c-c8fe-11ed-9459-93612e419c43
SERVER: Linux/4.9.206-axis5, UPnP/1.0, Portable SDK for UPnP devices/1.14.6
X-User-Agent: redsonic
ST: upnp:rootdevice
USN: uuid:Upnp-BasicDevice-1_0-B8A44F26437D::upnp:rootdevice

```

**Comment by ivanempire** [comment]
![image](https://user-images.githubusercontent.com/1571060/227088578-62773a29-95cb-49ec-89a8-be428837ee5d.png)

Yeah that's not an ideal "feature" of the protocol. Let me peruse the entire spec to see what else should be supported from 1.0 for full backwards compatibility, I know the `EXT` header field is supported now only because it was a low-hanging fruit. I saw your implementation and that looks good, I'll update this bug to see if anything else has to be done outside of that.
